# Generated by Django 4.0.6 on 2022-09-04 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0004_remove_post_categoria_post_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cuerpo',
            field=models.CharField(max_length=5000),
        ),
    ]
