# Generated by Django 4.0.6 on 2022-08-20 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_MVTProyectoFinalCoder', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Office',
        ),
    ]
