# Generated by Django 4.0.6 on 2022-08-20 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=100)),
                ('comentario', models.CharField(max_length=500)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('correo_electronico', models.CharField(max_length=100)),
            ],
        ),
    ]
