# Generated by Django 4.0.6 on 2022-08-26 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App_Office', '0001_initial'),
        ('App_Car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaSalida', models.DateField()),
                ('horaSalida', models.TimeField()),
                ('fechaLlegada', models.DateField()),
                ('horaLlegada', models.TimeField()),
                ('nombreConductor', models.CharField(max_length=200)),
                ('identificacionConductor', models.CharField(max_length=200)),
                ('telefonoConductor', models.CharField(max_length=50)),
                ('edadConductor', models.IntegerField()),
                ('correoConductor', models.CharField(max_length=200)),
                ('oficinaLlegada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oficinaLlegada', to='App_Office.office')),
                ('oficinaSalida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oficinaSalida', to='App_Office.office')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Car.car')),
            ],
        ),
    ]
